#!/bin/sh

#
# (optional) Copy this file to .git/hooks/
#

echo "Running Custom Commit Hook..."
echo "Testing build..."

deno task build

if [ $? -ne 0 ]; then
    echo "Error: Build failed"
    exit 1
fi
